CREATE DATABASE VET;

-- CONNECT TO THE VET DATABASE IF YOU HAVE NOT ALREADY DONE SO
\c VET

DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS PETS;
DROP TABLE IF EXISTS RESERVATIONS;

CREATE TABLE ROLES (
  RID SERIAL PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL UNIQUE CHECK (NAME IN ('ADMIN','VET','CLIENT'))
);

CREATE TABLE USERS(
  UID SERIAL PRIMARY KEY,
  EMAIL VARCHAR(60) NOT NULL UNIQUE,
  USERNAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(80) NOT NULL,
  ROLE_ID INT NOT NULL DEFAULT 3,
  FOREIGN KEY (ROLE_ID) REFERENCES ROLES(RID)
);

CREATE TABLE PETS(
  PID SERIAL PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  SPECIES VARCHAR(50) NOT NULL,
  BREED VARCHAR(50),
  OWNER INT NOT NULL,
  FOREIGN KEY (OWNER) REFERENCES USERS(UID)
);

CREATE TABLE RESERVATIONS(
  RESERVATION_ID SERIAL PRIMARY KEY,
  PET INT NOT NULL,
  VET INT NOT NULL,
  RESERVATION_DATE DATE NOT NULL,
  DESCRIPTION TEXT,
  FOREIGN KEY (PET) REFERENCES PETS(PID),
  FOREIGN KEY (VET) REFERENCES USERS(UID)
);
